keep-going: True
rerun-incomplete: True
rerun-triggers: "mtime"
printshellcmds: True
restart-times: 3
# singularity
use-singularity: True
singularity-args: "--bind /home/singularity_project/apabenchmark:/home/singularity_project/apabenchmark --cpus 8"
